// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokemonDraftAPI.Database;

#nullable disable

namespace PokemonDraftAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250903222520_Mochila")]
    partial class Mochila
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PokemonDraftAPI.Database.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CounterPokemonId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CounterPokemonId");

                    b.HasIndex("PokemonId", "CounterPokemonId")
                        .IsUnique();

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Entities.UserPokemon", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PokemonId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PokemonId");

                    b.HasIndex("PokemonId");

                    b.ToTable("UserPokemons");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Counter", b =>
                {
                    b.HasOne("PokemonDraftAPI.Database.Pokemon", "CounterPokemon")
                        .WithMany()
                        .HasForeignKey("CounterPokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PokemonDraftAPI.Database.Pokemon", "Pokemon")
                        .WithMany("Counters")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CounterPokemon");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Entities.UserPokemon", b =>
                {
                    b.HasOne("PokemonDraftAPI.Database.Pokemon", "Pokemon")
                        .WithMany("UserPokemons")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokemonDraftAPI.Database.Entities.User", "User")
                        .WithMany("UserPokemons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Entities.User", b =>
                {
                    b.Navigation("UserPokemons");
                });

            modelBuilder.Entity("PokemonDraftAPI.Database.Pokemon", b =>
                {
                    b.Navigation("Counters");

                    b.Navigation("UserPokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
